# Generated by Django 4.2 on 2023-05-07 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AndroidApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="member_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
