# Generated by Django 4.2 on 2023-05-04 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("category_title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=600)),
                (
                    "course_cover_image",
                    models.ImageField(
                        default="default.jpg", upload_to="images/course_cover/"
                    ),
                ),
                ("length", models.TimeField()),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="member",
            name="id",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="id",
        ),
        migrations.AddField(
            model_name="member",
            name="member_id",
            field=models.IntegerField(
                default=-1, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(default="+980000000000", max_length=13),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="images/profile/"),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="membership",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Authentication.member"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="membership_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "purchase_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("place_at", models.CharField(max_length=20)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("successful", "Successful"),
                            ("unsuccessful", "Unsuccessful"),
                            ("suspended", "Suspended"),
                        ],
                        default="unsuccessful",
                        max_length=20,
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.course",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "program_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField()),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalInfo",
            fields=[
                (
                    "physical_info_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[django.core.validators.MaxValueValidator(220)]
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        validators=[django.core.validators.MaxValueValidator(200)]
                    ),
                ),
                ("birth_date", models.DateField()),
                ("gender", models.CharField(max_length=13)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseVideo",
            fields=[
                (
                    "video_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("video_title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("length", models.TimeField()),
                (
                    "video_file",
                    models.FileField(default="default.mp4", upload_to="video/"),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.category",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "address_id",
                    models.IntegerField(
                        default=-1, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("country", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("address", models.TextField(max_length=300)),
                (
                    "address_phone",
                    models.CharField(default="+982100000000", max_length=13),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.member",
                    ),
                ),
            ],
        ),
    ]
