# Generated by Django 4.2 on 2023-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_category_course_remove_member_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="length",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="coursevideo",
            name="length",
            field=models.DurationField(),
        ),
    ]
