# Generated by Django 4.2 on 2023-05-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_category_course_alter_member_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecategoryrelationships",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_id",
                to="Authentication.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="coursecategoryrelationships",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_based_category",
                to="Authentication.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="coursememberrelationships",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course2member",
                to="Authentication.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="coursememberrelationships",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member2course",
                to=settings.AUTH_USER_MODEL,
                verbose_name="member",
            ),
        ),
    ]
