# Generated by Django 4.2 on 2023-05-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_alter_course_length_alter_coursevideo_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="physicalinfo",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("non", "Not Preferred")],
                default="non",
                max_length=20,
            ),
        ),
    ]
