# Generated by Django 4.2 on 2023-04-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
