# Generated by Django 4.2 on 2023-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_alter_member_options_alter_member_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="created_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
